version: '2'
services:
  web:
    image: python
    working_dir: /code
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/code
